### PR TITLE
Update spaghetti.md

### PR DESCRIPTION
**Pull request by wesleysfng**
## 🎯 Objective

Added title, portions, and time

## 🛠️ Changes made

New Time
New Portions
New Time

## 👥 Who needs to review this Pull Request? 

@craig-kc

### CODE REVIEW

**Comment by wesleysfng** [comment]
Thanks @craig-kc for your update

**Comment by craig-kc** [comment]
Looks good!

**Comment by korawatt** [comment]
👍 😎

**Comment by craig-kc** [comment]
What about breadsticks?

**Comment by wesleysfng** [comment]
No breadsticks - i dont like sorry 👎

**Pull request merged**
