### PR TITLE
Group branch 1

### PR DESCRIPTION
**Pull request by josephyuberkeley**
## 🎯 Objective

all 6 Team members added commits to both recipes (dinner and breakfast)

## 🛠️ Changes made

@wesleysfng  @craig-kc added commits to the "group-branch-1" under Breakfast.md file
@korawatt created patch3 branch that merged into "group-branch-1" with commits also in the Breakfast.md file

@cheriekwok @kichimori @josephyuberkeley added commits on the "group-branch-1" under Dinner.md file.

## 👥 Who needs to review this Pull Request? 

@wesleysfng @korawatt 

_@mention some teammates to review your work._

@wesleysfng 
@korawatt 
@cheriekwok 
@kichimori 
@craig-kc 
@josephyuberkeley

### CODE REVIEW

**Review by korawatt — APPROVED** [review]

**Comment by korawatt** [comment]
Look good to me!

**Review by wesleysfng — APPROVED** [review]
Looks great - I changed the conflicts so that they would work!

**Comment by josephyuberkeley** [comment]
Awesome, thanks @wesleysfng !

**Review by cheriekwok — APPROVED** [review]
Looks good to me!

**Pull request merged**
